### ISSUE TITLE
Autoswitch API missing in 1.18.2

### ISSUE THREAD

**Issue by NoEnd-yt** [dexman545/Fabric-Autoswitch#38]
Hi!
I opened Minecraft 1.18.2 with Autoswitch and got this error about "Autoswitch API missing".
I am using MultiMC 5 on Manjaro Linux.
Here is the log:
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install autoswitch-api, any version between 1.1.0 (inclusive) and 2- (exclusive).
Unmet dependency listing:
	 - Mod 'AutoSwitch' (autoswitch) 4.0.1-alpha.1 requires any version between 1.1.0 (inclusive) and 2- (exclusive) of autoswitch-api, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

Please tell me if you know what is causing the issue.
Also, here is my mod config, if that helps:
```
accurate-block-placement-1.0.11.jar
animatica-0.3+1.18.jar
antighost-1.18-fabric0.43.1-1.1.4.jar
appleskin-fabric-mc1.18-2.2.0.jar
architectury-3.4.9.jar
autoconfig1u-3.3.1.jar
autoswitch-4.0.1-alpha.1.jar
AxesAreWeapons-1.5.1-fabric-1.17.1.jar
BetterCmdBlockFabric-1.18.1-2.5.8.jar
betterdroppeditems-1.3.1-21w37a.jar
BetterF3-1.2.3-Fabric-1.18.2.jar
bettermounthud-1.1.3.jar
boathud-1.0.0.jar
bobby-3.1.0.jar.disabled
breakprogress-1.0.1.jar
CameraOverhaul-1.3.0-fabric-universal.jar
can-i-mine-this-block-1.1.0.jar
Capes-1.2.2+1.18.jar
cem-0.7.0.jar
charmonium-fabric-1.18-4.0.0.jar
chatplus-1.18.1-2.1.6.jar
CITResewn-0.8.2+1.18.1.jar
cloth-api-3.0.55.jar
cloth-config-6.1.48-fabric.jar
colorfulsubtitles-1.0.0.jar
completeconfig-lib-1.3.3.jar
continuity-1.0.3+1.18.jar
Controlling-fabric-1.18.1-9.0.11.jar
Couplings-1.7.1+1.18.jar
dark-loading-screen-1.6.11.jar
DCCH-2.0+1.17.jar
deathlog-0.2.7+1.18.jar
DistantHorizons-1.6.2a-1.18.1.jar
DripSounds-1.18-0.3.0.jar
dynamic-fps-2.0.6.jar
DynamicSoundFilters-1.3.0+1.18.jar
EnchantmentDescriptions-Fabric-1.18.1-9.0.9.jar
enhancedblockentities-0.5+1.18.jar
EntityCulling-Fabric-1.3.3.jar
extrasounds-2.2.0+1.18.jar
fabric-api-0.47.8+1.18.2.jar
fabrication-1.18-2.3.0_01.jar
fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
fabrilous-updater-2.5+1.18.1.jar
ferritecore-4.0.0-fabric.jar
flytre_lib-1.18.1-1.6.4-fabric.jar
ForgeConfigAPIPort-v3.1.1-1.18.1-Fabric.jar
freelook-1.1.0.jar
Gamma-Utils-1.5.6-mc1.18.2.jar
IKnowWhatImDoing-4.0.0-fabric.jar
indium-1.0.2-alpha1+mc1.18.jar
inspecio-1.2.1+1.18.jar
'InventoryHUD-fabric-[1.18]+-3.4.2.jar'
InventoryProfilesNext-fabric-1.18-1.2.3.jar
iris-mc1.18.1-1.1.4.jar
itemscroller-fabric-1.18.0-0.15.0.jar
krypton-0.1.6.jar.disabled
Ksyxis-1.1.jar
lambdabettergrass-1.2.2+1.17.jar
lambdynamiclights-2.1.0+1.17.jar
language-reload-1.2.1.jar
lazydfu-0.1.2.jar
lithium-fabric-mc1.18.1-0.7.8.jar.disabled
malilib-fabric-1.18.0-0.10.0-dev.26.jar
megane-6.2.0.jar
MemoryUsageScreen-1.17-1.2.jar
modmenu-3.0.1.jar
morechathistory-1.18-1.1.0.jar
multiworldborders-1.3-fabric-1.18.jar
no-nether-portal-overlay-1.0.2.jar
notenoughcrashes-4.1.3+1.18.1-fabric.jar
okzoomer-5.0.0-beta.3+1.17.1.jar
PickUpNotifier-v3.1.0-1.18.1-Fabric.jar
pistorder-mc1.18-v1.4.4-fabric.jar
PresenceFootsteps-1.4.0.jar
PuzzlesLib-v3.1.3-1.18.1-Fabric.jar
rebind-all-the-keys-1.1.1+1.18.jar
reeses_sodium_options-mc1.18.1-1.3.0.jar
rer-2.3.0.jar
right-click-harvest-1.1.0+1.18.1-fabric.jar
RoughlyEnoughItems-7.1.361.jar
second-chance-1.3.0.jar
slight-gui-modifications-2.0.2.jar
smoothboot-fabric-1.18-1.7.0.jar
SmoothScrollingEverywhere-3.0.4.jar
sodium-extra-mc1.18-0.3.7.jar
sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar
starlight-1.0.2+fabric.89b8d9f.jar
stendhal-1.2.0-1.18.jar
'Trajectory Preview-1.0-1.18.1.jar'
uglyscoreboardfix-2.4.0.jar
voicechat-fabric-1.18.1-2.2.7.jar.disabled
whyamionfire-1.1.1.jar
wthit-fabric-4.4.1.jar
Xaeros_Minimap_21.23.1_Fabric_1.18.jar
XaerosWorldMap_1.19.1_Fabric_1.18.jar
```

**Comment by dexman545** [comment]
Uploaded new version 4.0.1 which should fix this.

**Comment by NoEnd-yt** [comment]
Hum, sorry to reopen the issue, but I still get this bug.
Here is the error:
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install autoswitch-api, any version between 1.1.0 (inclusive) and 2- (exclusive).
Unmet dependency listing:
	 - Mod 'AutoSwitch' (autoswitch) 4.0.0 requires any version between 1.1.0 (inclusive) and 2- (exclusive) of autoswitch-api, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
Here is my mod config:
```
accurate-block-placement-1.0.11.jar
animatica-0.3+1.18.jar
antighost-1.18-fabric0.43.1-1.1.4.jar
appleskin-fabric-mc1.18-2.2.0.jar
architectury-3.4.9.jar
autoconfig1u-3.3.1.jar
autoswitch-4.0.1.jar
AxesAreWeapons-1.5.1-fabric-1.17.1.jar
BetterCmdBlockFabric-1.18.1-2.5.8.jar
betterdroppeditems-1.3.1-21w37a.jar
BetterF3-1.2.3-Fabric-1.18.2.jar
bettermounthud-1.1.3.jar
boathud-1.0.0.jar
bobby-3.1.0.jar.disabled
breakprogress-1.0.1.jar
CameraOverhaul-1.3.0-fabric-universal.jar
can-i-mine-this-block-1.1.0.jar
Capes-1.2.2+1.18.jar
cem-0.7.0.jar
charmonium-fabric-1.18-4.0.0.jar
chatplus-1.18.1-2.1.6.jar
CITResewn-0.8.2+1.18.1.jar
cloth-api-3.0.55.jar
cloth-config-6.1.48-fabric.jar
colorfulsubtitles-1.0.0.jar
completeconfig-lib-1.3.3.jar
continuity-1.0.3+1.18.jar
Controlling-fabric-1.18.1-9.0.11.jar
Couplings-1.7.1+1.18.jar
dark-loading-screen-1.6.11.jar
DCCH-2.0+1.17.jar
deathlog-0.2.7+1.18.jar
DistantHorizons-1.6.2a-1.18.1.jar
DripSounds-1.18-0.3.0.jar
dynamic-fps-2.0.6.jar
DynamicSoundFilters-1.3.0+1.18.jar
EnchantmentDescriptions-Fabric-1.18.1-9.0.9.jar
enhancedblockentities-0.5+1.18.jar
EntityCulling-Fabric-1.3.3.jar
extrasounds-2.2.0+1.18.jar
fabric-api-0.47.8+1.18.2.jar
fabrication-1.18-2.3.0_01.jar
fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
fabrilous-updater-2.5+1.18.1.jar
ferritecore-4.0.0-fabric.jar
flytre_lib-1.18.1-1.6.4-fabric.jar
ForgeConfigAPIPort-v3.1.1-1.18.1-Fabric.jar
freelook-1.1.0.jar
Gamma-Utils-1.5.6-mc1.18.2.jar
IKnowWhatImDoing-4.0.0-fabric.jar
indium-1.0.2-alpha1+mc1.18.jar
inspecio-1.2.1+1.18.jar
'InventoryHUD-fabric-[1.18]+-3.4.2.jar'
InventoryProfilesNext-fabric-1.18-1.2.3.jar
iris-mc1.18.1-1.1.4.jar
itemscroller-fabric-1.18.0-0.15.0.jar
krypton-0.1.6.jar.disabled
Ksyxis-1.1.jar
lambdabettergrass-1.2.2+1.17.jar
lambdynamiclights-2.1.0+1.17.jar
language-reload-1.2.1.jar
lazydfu-0.1.2.jar
lithium-fabric-mc1.18.2-0.7.9.jar
malilib-fabric-1.18.0-0.10.0-dev.26.jar
megane-6.2.0.jar
MemoryUsageScreen-1.17-1.2.jar
modmenu-3.0.1.jar
morechathistory-1.18-1.1.0.jar
multiworldborders-1.3-fabric-1.18.jar
no-nether-portal-overlay-1.0.2.jar
notenoughcrashes-4.1.3+1.18.1-fabric.jar
okzoomer-5.0.0-beta.3+1.17.1.jar
PickUpNotifier-v3.1.0-1.18.1-Fabric.jar
pistorder-mc1.18-v1.4.4-fabric.jar
PresenceFootsteps-1.4.0.jar
PuzzlesLib-v3.1.3-1.18.1-Fabric.jar
rebind-all-the-keys-1.1.1+1.18.jar
reeses_sodium_options-mc1.18.1-1.3.0.jar
rer-2.3.0.jar
right-click-harvest-1.1.0+1.18.1-fabric.jar
RoughlyEnoughItems-7.1.361.jar
second-chance-1.3.0.jar
slight-gui-modifications-2.0.2.jar
smoothboot-fabric-1.18-1.7.0.jar
SmoothScrollingEverywhere-3.0.4.jar
sodium-extra-mc1.18-0.3.7.jar
sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar
starlight-1.0.2+fabric.89b8d9f.jar
stendhal-1.2.0-1.18.jar
'Trajectory Preview-1.0-1.18.1.jar'
uglyscoreboardfix-2.4.0.jar
voicechat-fabric-1.18.1-2.2.7.jar.disabled
whyamionfire-1.1.1.jar
wthit-fabric-4.4.1.jar
Xaeros_Minimap_21.23.1_Fabric_1.18.jar
XaerosWorldMap_1.19.1_Fabric_1.18.jar
```
